
services:
  orders-db:
    image: postgres:15
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders
    ports: ["5433:5432"]
    volumes: ["orders_data:/var/lib/postgresql/data"]
  payments-db:
    image: postgres:15
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments
    ports: ["5434:5432"]
    volumes: ["payments_data:/var/lib/postgresql/data"]
  payments-service:
    build: ./payments-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payments-db:5432/payments
      SPRING_DATASOURCE_USERNAME: payments
      SPRING_DATASOURCE_PASSWORD: payments
    depends_on: [payments-db]
    ports: ["8082:8080"]
  orders-service:
    build: ./orders-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://orders-db:5432/orders
      SPRING_DATASOURCE_USERNAME: orders
      SPRING_DATASOURCE_PASSWORD: orders
      PAYMENTS_BASE_URL: http://payments-service:8080
    depends_on: [orders-db, payments-service]
    ports: ["8081:8080"]
volumes: {orders_data: {}, payments_data: {}}
